package org.option.db;

// Generated May 16, 2017 3:33:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsdinrId generated by hbm2java
 */
@Embeddable
public class UsdinrId implements java.io.Serializable {

	private Date date;
	private Date expiry;
	private float strick;

	public UsdinrId() {
	}

	public UsdinrId(Date date, Date expiry, float strick) {
		this.date = date;
		this.expiry = expiry;
		this.strick = strick;
	}

	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Expiry", nullable = false, length = 10)
	public Date getExpiry() {
		return this.expiry;
	}

	public void setExpiry(Date expiry) {
		this.expiry = expiry;
	}

	@Column(name = "Strick", nullable = false, precision = 12, scale = 0)
	public float getStrick() {
		return this.strick;
	}

	public void setStrick(float strick) {
		this.strick = strick;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsdinrId))
			return false;
		UsdinrId castOther = (UsdinrId) other;

		return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(
				castOther.getDate())))
				&& ((this.getExpiry() == castOther.getExpiry()) || (this.getExpiry() != null && castOther.getExpiry() != null && this.getExpiry()
						.equals(castOther.getExpiry()))) && (this.getStrick() == castOther.getStrick());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getExpiry() == null ? 0 : this.getExpiry().hashCode());
		result = 37 * result + (int) this.getStrick();
		return result;
	}

}
