package org.option.db;

// Generated May 16, 2017 3:33:56 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Usdinr generated by hbm2java
 */
@Entity
@Table(name = "USDINR", catalog = "stocksrin")
public class Usdinr implements java.io.Serializable {

	private UsdinrId id;
	private Integer ceOiValue;
	private Integer peOiValue;
	/*private Integer ceOiTotal;
	private Integer peOiTotal;*/

	public Usdinr() {
	}

	public Usdinr(UsdinrId id) {
		this.id = id;
	}

	public Usdinr(UsdinrId id, Integer ceOiValue, Integer peOiValue) {
		this.id = id;
		this.ceOiValue = ceOiValue;
		this.peOiValue = peOiValue;
		
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "date", column = @Column(name = "Date", nullable = false, length = 10)),
			@AttributeOverride(name = "expiry", column = @Column(name = "Expiry", nullable = false, length = 10)),
			@AttributeOverride(name = "strick", column = @Column(name = "Strick", nullable = false, precision = 12, scale = 0)) })
	public UsdinrId getId() {
		return this.id;
	}

	public void setId(UsdinrId id) {
		this.id = id;
	}

	@Column(name = "CE_OI_Value")
	public Integer getCeOiValue() {
		return this.ceOiValue;
	}

	public void setCeOiValue(Integer ceOiValue) {
		this.ceOiValue = ceOiValue;
	}

	@Column(name = "PE_OI_Value")
	public Integer getPeOiValue() {
		return this.peOiValue;
	}

	public void setPeOiValue(Integer peOiValue) {
		this.peOiValue = peOiValue;
	}


}
