package org.stocks.price;

// Generated May 26 2017 8:48:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NsePriceId generated by hbm2java
 */
@Embeddable
public class NsePriceId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1413140262205085990L;
	private String nseSymbol;
	private Date nseDate;

	public NsePriceId() {
	}

	public NsePriceId(String nseSymbol, Date nseDate) {
		this.nseSymbol = nseSymbol;
		this.nseDate = nseDate;
	}

	@Column(name = "nse_symbol", nullable = false,length = 50)
	public String getNseSymbol() {
		return this.nseSymbol;
	}

	public void setNseSymbol(String nseSymbol) {
		this.nseSymbol = nseSymbol;
	}

	@Column(name = "nse_date" ,nullable = false, length = 10)
	public Date getNseDate() {
		return this.nseDate;
	}

	public void setNseDate(Date nseDate) {
		this.nseDate = nseDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NsePriceId))
			return false;
		NsePriceId castOther = (NsePriceId) other;

		return ((this.getNseSymbol() == castOther.getNseSymbol()) || (this.getNseSymbol() != null && castOther.getNseSymbol() != null && this
				.getNseSymbol().equals(castOther.getNseSymbol())))
				&& ((this.getNseDate() == castOther.getNseDate()) || (this.getNseDate() != null && castOther.getNseDate() != null && this
						.getNseDate().equals(castOther.getNseDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNseSymbol() == null ? 0 : this.getNseSymbol().hashCode());
		result = 37 * result + (getNseDate() == null ? 0 : this.getNseDate().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "NsePriceId [nseSymbol=" + nseSymbol + " nseDate=" + nseDate + "]";
	}

}
