package org.stocks.price;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NsePrice generated by hbm2java
 */
@Entity
@Table(name = "NSE_PRICE", catalog = "stocksrin")
public class NsePrice implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8280077128948283029L;
	private NsePriceId id;
	private String nseOpen;
	private String nseHigh;
	private String nseLow;
	private String nseChange;
	private String nseClose;
	private String percantageChange;
	private String comments;

	public NsePrice() {
	}

	public NsePrice(NsePriceId id ,String nseClose) {
		this.id = id;
		this.nseClose = nseClose;
	}

	public NsePrice(NsePriceId id, String nseOpen, String nseHigh, String nseLow, String nseChange, String nseClose, String percantageChange,
			String comments) {
		this.id = id;
		this.nseOpen = nseOpen;
		this.nseHigh = nseHigh;
		this.nseLow = nseLow;
		this.nseChange = nseChange;
		this.nseClose = nseClose;
		this.percantageChange = percantageChange;
		this.comments = comments;
	}

	
	public NsePriceId getId() {
		return this.id;
	}

	public void setId(NsePriceId id) {
		this.id = id;
	}

	@Column(name = "nse_open", length = 50)
	public String getNseOpen() {
		return this.nseOpen;
	}

	public void setNseOpen(String nseOpen) {
		this.nseOpen = nseOpen;
	}

	@Column(name = "nse_high", length = 50)
	public String getNseHigh() {
		return this.nseHigh;
	}

	public void setNseHigh(String nseHigh) {
		this.nseHigh = nseHigh;
	}

	@Column(name = "nse_low", length = 50)
	public String getNseLow() {
		return this.nseLow;
	}

	public void setNseLow(String nseLow) {
		this.nseLow = nseLow;
	}

	@Column(name = "nse_change", length = 50)
	public String getNseChange() {
		return this.nseChange;
	}

	public void setNseChange(String nseChange) {
		this.nseChange = nseChange;
	}

	@Column(name = "nse_close", nullable = false, length = 50)
	public String getNseClose() {
		return this.nseClose;
	}

	public void setNseClose(String nseClose) {
		this.nseClose = nseClose;
	}

	@Column(name = "PercantageChange", length = 50)
	public String getPercantageChange() {
		return this.percantageChange;
	}

	public void setPercantageChange(String percantageChange) {
		this.percantageChange = percantageChange;
	}

	@Column(name = "Comments", length = 250)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Override
	public String toString() {
		return "NsePrice [id=" + id + " nseOpen=" + nseOpen + " nseHigh=" + nseHigh + " nseLow=" + nseLow + " nseChange=" + nseChange
				+ " nseClose=" + nseClose + " percantageChange=" + percantageChange + " comments=" + comments + " toString()=" + super.toString()
				+ "]";
	}

}
